// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: apps/metric/pb/metric.proto

package metric

import (
	resource "github.com/infraboard/cmdb/apps/resource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 统一多个云商的指标名称
type Metric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 资源类型
	// @gotags: json:"resource_type"
	ResourceType resource.Type `protobuf:"varint,1,opt,name=resource_type,json=resourceType,proto3,enum=infraboard.cmdb.resource.Type" json:"resource_type"`
	// 指标名称
	// @gotags: json:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	// 指标描述
	// @gotags: json:"describe"
	Describe string `protobuf:"bytes,3,opt,name=describe,proto3" json:"describe"`
	// 指标单位
	// @gotags: json:"unit"
	Unit string `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit"`
	// 指标的维度
	// @gotags: json:"dimensions"
	Dimensions []string `protobuf:"bytes,5,rep,name=dimensions,proto3" json:"dimensions"`
}

func (x *Metric) Reset() {
	*x = Metric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_metric_pb_metric_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_apps_metric_pb_metric_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_apps_metric_pb_metric_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetResourceType() resource.Type {
	if x != nil {
		return x.ResourceType
	}
	return resource.Type(0)
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *Metric) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Metric) GetDimensions() []string {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

var File_apps_metric_pb_metric_proto protoreflect.FileDescriptor

var file_apps_metric_pb_metric_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2f, 0x70, 0x62,
	0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x69,
	0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x6d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x1a, 0x1f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb1, 0x01, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x12, 0x43, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69,
	0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a,
	0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0x05, 0x0a, 0x03, 0x52, 0x50,
	0x43, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2f, 0x63, 0x6d, 0x64, 0x62, 0x2f,
	0x61, 0x70, 0x70, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_apps_metric_pb_metric_proto_rawDescOnce sync.Once
	file_apps_metric_pb_metric_proto_rawDescData = file_apps_metric_pb_metric_proto_rawDesc
)

func file_apps_metric_pb_metric_proto_rawDescGZIP() []byte {
	file_apps_metric_pb_metric_proto_rawDescOnce.Do(func() {
		file_apps_metric_pb_metric_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_metric_pb_metric_proto_rawDescData)
	})
	return file_apps_metric_pb_metric_proto_rawDescData
}

var file_apps_metric_pb_metric_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_apps_metric_pb_metric_proto_goTypes = []interface{}{
	(*Metric)(nil),     // 0: infraboard.cmdb.metric.Metric
	(resource.Type)(0), // 1: infraboard.cmdb.resource.Type
}
var file_apps_metric_pb_metric_proto_depIdxs = []int32{
	1, // 0: infraboard.cmdb.metric.Metric.resource_type:type_name -> infraboard.cmdb.resource.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apps_metric_pb_metric_proto_init() }
func file_apps_metric_pb_metric_proto_init() {
	if File_apps_metric_pb_metric_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_metric_pb_metric_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_metric_pb_metric_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_metric_pb_metric_proto_goTypes,
		DependencyIndexes: file_apps_metric_pb_metric_proto_depIdxs,
		MessageInfos:      file_apps_metric_pb_metric_proto_msgTypes,
	}.Build()
	File_apps_metric_pb_metric_proto = out.File
	file_apps_metric_pb_metric_proto_rawDesc = nil
	file_apps_metric_pb_metric_proto_goTypes = nil
	file_apps_metric_pb_metric_proto_depIdxs = nil
}
