// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: apps/lb/pb/lb.proto

package lb

import (
	resource "github.com/infraboard/cmdb/apps/resource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type STATUS int32

const (
	// 未知状态
	STATUS_UNKNOW STATUS = 0
	// 表示创建中
	STATUS_PENDING STATUS = 5
	// 表示运行中
	STATUS_RUNNING STATUS = 11
	// 表示实例已经锁定
	STATUS_LOCKED STATUS = 70
	// 表示停止
	STATUS_STOPPED STATUS = 80
	// 已销毁
	STATUS_DESTROYED STATUS = 90
)

// Enum value maps for STATUS.
var (
	STATUS_name = map[int32]string{
		0:  "UNKNOW",
		5:  "PENDING",
		11: "RUNNING",
		70: "LOCKED",
		80: "STOPPED",
		90: "DESTROYED",
	}
	STATUS_value = map[string]int32{
		"UNKNOW":    0,
		"PENDING":   5,
		"RUNNING":   11,
		"LOCKED":    70,
		"STOPPED":   80,
		"DESTROYED": 90,
	}
)

func (x STATUS) Enum() *STATUS {
	p := new(STATUS)
	*p = x
	return p
}

func (x STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_lb_pb_lb_proto_enumTypes[0].Descriptor()
}

func (STATUS) Type() protoreflect.EnumType {
	return &file_apps_lb_pb_lb_proto_enumTypes[0]
}

func (x STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use STATUS.Descriptor instead.
func (STATUS) EnumDescriptor() ([]byte, []int) {
	return file_apps_lb_pb_lb_proto_rawDescGZIP(), []int{0}
}

type LoadBalancer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"resource"
	Resource *resource.Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource"`
	// @gotags: json:"describe"
	Describe *Describe `protobuf:"bytes,3,opt,name=describe,proto3" json:"describe"`
}

func (x *LoadBalancer) Reset() {
	*x = LoadBalancer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_lb_pb_lb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadBalancer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBalancer) ProtoMessage() {}

func (x *LoadBalancer) ProtoReflect() protoreflect.Message {
	mi := &file_apps_lb_pb_lb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBalancer.ProtoReflect.Descriptor instead.
func (*LoadBalancer) Descriptor() ([]byte, []int) {
	return file_apps_lb_pb_lb_proto_rawDescGZIP(), []int{0}
}

func (x *LoadBalancer) GetResource() *resource.Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *LoadBalancer) GetDescribe() *Describe {
	if x != nil {
		return x.Describe
	}
	return nil
}

type Describe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 负载均衡实例的域名，仅公网传统型负载均衡实例才提供该字段
	// @gotags: json:"domain"
	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain"`
	// 状态变化的时间
	// @gotags: json:"status_at"
	StatusAt int64 `protobuf:"varint,2,opt,name=status_at,json=statusAt,proto3" json:"status_at"`
	// IP版本，可以设置为ipv4或者ipv6
	// @gotags: json:"ip_version"
	IpVersion string `protobuf:"bytes,3,opt,name=ip_version,json=ipVersion,proto3" json:"ip_version"`
	// 私网负载均衡实例的网络类型 vpc：专有网络实例 classic：经典网络实例
	// @gotags: json:"network_type"
	NetworkType string `protobuf:"bytes,4,opt,name=network_type,json=networkType,proto3" json:"network_type"`
	// 带宽
	// @gotags: json:"band_width"
	BandWidth int32 `protobuf:"varint,5,opt,name=band_width,json=bandWidth,proto3" json:"band_width"`
}

func (x *Describe) Reset() {
	*x = Describe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_lb_pb_lb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Describe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Describe) ProtoMessage() {}

func (x *Describe) ProtoReflect() protoreflect.Message {
	mi := &file_apps_lb_pb_lb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Describe.ProtoReflect.Descriptor instead.
func (*Describe) Descriptor() ([]byte, []int) {
	return file_apps_lb_pb_lb_proto_rawDescGZIP(), []int{1}
}

func (x *Describe) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Describe) GetStatusAt() int64 {
	if x != nil {
		return x.StatusAt
	}
	return 0
}

func (x *Describe) GetIpVersion() string {
	if x != nil {
		return x.IpVersion
	}
	return ""
}

func (x *Describe) GetNetworkType() string {
	if x != nil {
		return x.NetworkType
	}
	return ""
}

func (x *Describe) GetBandWidth() int32 {
	if x != nil {
		return x.BandWidth
	}
	return 0
}

type LoadBalancerSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 列表项
	Items []*LoadBalancer `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// 总数量
	Total int64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *LoadBalancerSet) Reset() {
	*x = LoadBalancerSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_lb_pb_lb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadBalancerSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBalancerSet) ProtoMessage() {}

func (x *LoadBalancerSet) ProtoReflect() protoreflect.Message {
	mi := &file_apps_lb_pb_lb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBalancerSet.ProtoReflect.Descriptor instead.
func (*LoadBalancerSet) Descriptor() ([]byte, []int) {
	return file_apps_lb_pb_lb_proto_rawDescGZIP(), []int{2}
}

func (x *LoadBalancerSet) GetItems() []*LoadBalancer {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *LoadBalancerSet) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_apps_lb_pb_lb_proto protoreflect.FileDescriptor

var file_apps_lb_pb_lb_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x6c, 0x62, 0x2f, 0x70, 0x62, 0x2f, 0x6c, 0x62, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x73, 0x6c, 0x62, 0x1a, 0x1f, 0x61, 0x70, 0x70, 0x73,
	0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x89, 0x01, 0x0a, 0x0c,
	0x4c, 0x6f, 0x61, 0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x63, 0x6d, 0x64, 0x62,
	0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x08,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x63, 0x6d, 0x64, 0x62,
	0x2e, 0x73, 0x6c, 0x62, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x08, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x22, 0xa0, 0x01, 0x0a, 0x08, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x70, 0x5f,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69,
	0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x62,
	0x61, 0x6e, 0x64, 0x5f, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x62, 0x61, 0x6e, 0x64, 0x57, 0x69, 0x64, 0x74, 0x68, 0x22, 0x60, 0x0a, 0x0f, 0x4c, 0x6f,
	0x61, 0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x53, 0x65, 0x74, 0x12, 0x37, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x69,
	0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x73,
	0x6c, 0x62, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x2a, 0x56, 0x0a, 0x06,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x05, 0x12,
	0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x0b, 0x12, 0x0a, 0x0a, 0x06,
	0x4c, 0x4f, 0x43, 0x4b, 0x45, 0x44, 0x10, 0x46, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x4f, 0x50,
	0x50, 0x45, 0x44, 0x10, 0x50, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x45, 0x53, 0x54, 0x52, 0x4f, 0x59,
	0x45, 0x44, 0x10, 0x5a, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2f, 0x63, 0x6d,
	0x64, 0x62, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x6c, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_apps_lb_pb_lb_proto_rawDescOnce sync.Once
	file_apps_lb_pb_lb_proto_rawDescData = file_apps_lb_pb_lb_proto_rawDesc
)

func file_apps_lb_pb_lb_proto_rawDescGZIP() []byte {
	file_apps_lb_pb_lb_proto_rawDescOnce.Do(func() {
		file_apps_lb_pb_lb_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_lb_pb_lb_proto_rawDescData)
	})
	return file_apps_lb_pb_lb_proto_rawDescData
}

var file_apps_lb_pb_lb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apps_lb_pb_lb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_apps_lb_pb_lb_proto_goTypes = []interface{}{
	(STATUS)(0),               // 0: infraboard.cmdb.slb.STATUS
	(*LoadBalancer)(nil),      // 1: infraboard.cmdb.slb.LoadBalancer
	(*Describe)(nil),          // 2: infraboard.cmdb.slb.Describe
	(*LoadBalancerSet)(nil),   // 3: infraboard.cmdb.slb.LoadBalancerSet
	(*resource.Resource)(nil), // 4: infraboard.cmdb.resource.Resource
}
var file_apps_lb_pb_lb_proto_depIdxs = []int32{
	4, // 0: infraboard.cmdb.slb.LoadBalancer.resource:type_name -> infraboard.cmdb.resource.Resource
	2, // 1: infraboard.cmdb.slb.LoadBalancer.describe:type_name -> infraboard.cmdb.slb.Describe
	1, // 2: infraboard.cmdb.slb.LoadBalancerSet.items:type_name -> infraboard.cmdb.slb.LoadBalancer
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_apps_lb_pb_lb_proto_init() }
func file_apps_lb_pb_lb_proto_init() {
	if File_apps_lb_pb_lb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_lb_pb_lb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadBalancer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_lb_pb_lb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Describe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_lb_pb_lb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadBalancerSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_lb_pb_lb_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_lb_pb_lb_proto_goTypes,
		DependencyIndexes: file_apps_lb_pb_lb_proto_depIdxs,
		EnumInfos:         file_apps_lb_pb_lb_proto_enumTypes,
		MessageInfos:      file_apps_lb_pb_lb_proto_msgTypes,
	}.Build()
	File_apps_lb_pb_lb_proto = out.File
	file_apps_lb_pb_lb_proto_rawDesc = nil
	file_apps_lb_pb_lb_proto_goTypes = nil
	file_apps_lb_pb_lb_proto_depIdxs = nil
}
