// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.1
// source: apps/bill/pb/order.proto

package bill

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ORDER_TYPE int32

const (
	// 资源新增订单
	ORDER_TYPE_NEW ORDER_TYPE = 0
	// 续费。
	ORDER_TYPE_RENEW ORDER_TYPE = 1
	// 升级。
	ORDER_TYPE_UPGRADE ORDER_TYPE = 2
	// 退款
	ORDER_TYPE_REFUND ORDER_TYPE = 3
)

// Enum value maps for ORDER_TYPE.
var (
	ORDER_TYPE_name = map[int32]string{
		0: "NEW",
		1: "RENEW",
		2: "UPGRADE",
		3: "REFUND",
	}
	ORDER_TYPE_value = map[string]int32{
		"NEW":     0,
		"RENEW":   1,
		"UPGRADE": 2,
		"REFUND":  3,
	}
)

func (x ORDER_TYPE) Enum() *ORDER_TYPE {
	p := new(ORDER_TYPE)
	*p = x
	return p
}

func (x ORDER_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ORDER_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_bill_pb_order_proto_enumTypes[0].Descriptor()
}

func (ORDER_TYPE) Type() protoreflect.EnumType {
	return &file_apps_bill_pb_order_proto_enumTypes[0]
}

func (x ORDER_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ORDER_TYPE.Descriptor instead.
func (ORDER_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_apps_bill_pb_order_proto_rawDescGZIP(), []int{0}
}

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 订单类型
	// @gotags: json:"type"
	Type ORDER_TYPE `protobuf:"varint,1,opt,name=type,proto3,enum=infraboard.cmdb.bill.ORDER_TYPE" json:"type"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_bill_pb_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_apps_bill_pb_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_apps_bill_pb_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetType() ORDER_TYPE {
	if x != nil {
		return x.Type
	}
	return ORDER_TYPE_NEW
}

var File_apps_bill_pb_order_proto protoreflect.FileDescriptor

var file_apps_bill_pb_order_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x62, 0x69, 0x6c, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x69, 0x6e, 0x66, 0x72,
	0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x62, 0x69, 0x6c, 0x6c,
	0x22, 0x3d, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x62, 0x69, 0x6c, 0x6c, 0x2e, 0x4f,
	0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x2a,
	0x39, 0x0a, 0x0a, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x07, 0x0a,
	0x03, 0x4e, 0x45, 0x57, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x4e, 0x45, 0x57, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x50, 0x47, 0x52, 0x41, 0x44, 0x45, 0x10, 0x02, 0x12, 0x0a,
	0x0a, 0x06, 0x52, 0x45, 0x46, 0x55, 0x4e, 0x44, 0x10, 0x03, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x2f, 0x63, 0x6d, 0x64, 0x62, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x62, 0x69,
	0x6c, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apps_bill_pb_order_proto_rawDescOnce sync.Once
	file_apps_bill_pb_order_proto_rawDescData = file_apps_bill_pb_order_proto_rawDesc
)

func file_apps_bill_pb_order_proto_rawDescGZIP() []byte {
	file_apps_bill_pb_order_proto_rawDescOnce.Do(func() {
		file_apps_bill_pb_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_bill_pb_order_proto_rawDescData)
	})
	return file_apps_bill_pb_order_proto_rawDescData
}

var file_apps_bill_pb_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apps_bill_pb_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_apps_bill_pb_order_proto_goTypes = []interface{}{
	(ORDER_TYPE)(0), // 0: infraboard.cmdb.bill.ORDER_TYPE
	(*Order)(nil),   // 1: infraboard.cmdb.bill.Order
}
var file_apps_bill_pb_order_proto_depIdxs = []int32{
	0, // 0: infraboard.cmdb.bill.Order.type:type_name -> infraboard.cmdb.bill.ORDER_TYPE
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apps_bill_pb_order_proto_init() }
func file_apps_bill_pb_order_proto_init() {
	if File_apps_bill_pb_order_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_bill_pb_order_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_bill_pb_order_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_bill_pb_order_proto_goTypes,
		DependencyIndexes: file_apps_bill_pb_order_proto_depIdxs,
		EnumInfos:         file_apps_bill_pb_order_proto_enumTypes,
		MessageInfos:      file_apps_bill_pb_order_proto_msgTypes,
	}.Build()
	File_apps_bill_pb_order_proto = out.File
	file_apps_bill_pb_order_proto_rawDesc = nil
	file_apps_bill_pb_order_proto_goTypes = nil
	file_apps_bill_pb_order_proto_depIdxs = nil
}
