[app]
name = "cmdb"
http_host = "0.0.0.0"
http_port = "8060"
grpc_host = "0.0.0.0"
grpc_port = "18060"
key  = "this is your app key"

[mysql]
host = "127.0.0.1"
port = "3306"
username = "root"
password = "123456"
database = "cmdb"

[mcenter]
address = "127.0.0.1:18010"
client_id = "xxx"
client_credential = "xxx"

[log]
level = "debug"
format = "text"
to = "stdout"