[app]
name = "cmdb"
http_host = "127.0.0.1"
http_port = "8060"
grpc_host = "127.0.0.1"
grpc_port = "18060"
key  = "this is your app key"

[mysql]
host = "127.0.0.1"
port = "3306"
username = "root"
password = "123456"
database = "cmdb"

[mcenter]
adress="127.0.0.1:18010"
client_id="EePde6X49zWv57CGV7waI0x6"
client_secret="PkFl6mutz53zHTzgtYh06exiHuqMxiBG"

[log]
level = "debug"
path = "logs"
format = "text"
to = "stdout"
