// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: apps/eip/pb/eip.proto

package eip

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	SyncEIP(ctx context.Context, in *EIP, opts ...grpc.CallOption) (*EIP, error)
	QueryEIP(ctx context.Context, in *QueryEIPRequest, opts ...grpc.CallOption) (*EIPSet, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) SyncEIP(ctx context.Context, in *EIP, opts ...grpc.CallOption) (*EIP, error) {
	out := new(EIP)
	err := c.cc.Invoke(ctx, "/infraboard.cmdb.eip.Service/SyncEIP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) QueryEIP(ctx context.Context, in *QueryEIPRequest, opts ...grpc.CallOption) (*EIPSet, error) {
	out := new(EIPSet)
	err := c.cc.Invoke(ctx, "/infraboard.cmdb.eip.Service/QueryEIP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	SyncEIP(context.Context, *EIP) (*EIP, error)
	QueryEIP(context.Context, *QueryEIPRequest) (*EIPSet, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) SyncEIP(context.Context, *EIP) (*EIP, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncEIP not implemented")
}
func (UnimplementedServiceServer) QueryEIP(context.Context, *QueryEIPRequest) (*EIPSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryEIP not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_SyncEIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EIP)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).SyncEIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infraboard.cmdb.eip.Service/SyncEIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).SyncEIP(ctx, req.(*EIP))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_QueryEIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).QueryEIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infraboard.cmdb.eip.Service/QueryEIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).QueryEIP(ctx, req.(*QueryEIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infraboard.cmdb.eip.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncEIP",
			Handler:    _Service_SyncEIP_Handler,
		},
		{
			MethodName: "QueryEIP",
			Handler:    _Service_QueryEIP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/eip/pb/eip.proto",
}
